[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "e9dee331aafdba31287111f5b8db7b2c78d6bd6a"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "fd14305019e1c14da63e6d1434ca0daee22ff8aad4e002d2907182967103ec4f"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v8.3.0%2B0/ElectronJS-8.3.0+0-x86_64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "3d70663c9f42b1421093ec48eadd17147427f249"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "1a68078cde42f30f2a71be96d9a949f793691d861ee753709886101af3c836e8"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v8.3.0%2B0/ElectronJS-8.3.0+0-aarch64-linux-gnu.tar.gz"
[[electronjs_app]]
arch = "armv7l"
git-tree-sha1 = "c83d55924178ad0f8708ab7426254698ff6dbae8"
libc = "glibc"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "ed3a1c152922409dc40f6d3112c368facb79ca2302d3bd0608b3836a3ae83dde"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v8.3.0%2B0/ElectronJS-8.3.0+0-arm-linux-gnueabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "e9dee331aafdba31287111f5b8db7b2c78d6bd6a"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "974b36d300785be6edc4de8ee785ac58a62c7dd560799e745e2ba49abcb74cb9"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v8.3.0%2B0/ElectronJS-8.3.0+0-x86_64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "aarch64"
git-tree-sha1 = "3d70663c9f42b1421093ec48eadd17147427f249"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "71239b68ccca5628cb6fd21a9388c182da7f2f5ab7524b6ef518576d41ba3da6"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v8.3.0%2B0/ElectronJS-8.3.0+0-aarch64-linux-musl.tar.gz"
[[electronjs_app]]
arch = "armv7l"
git-tree-sha1 = "c83d55924178ad0f8708ab7426254698ff6dbae8"
libc = "musl"
os = "linux"

    [[electronjs_app.download]]
    sha256 = "3bfb0b8d3739c4118386a5f7f599a7aef39d4a75854a26a4f9b0931696d897c2"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v8.3.0%2B0/ElectronJS-8.3.0+0-arm-linux-musleabihf.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "bd619c624682cfd8a3b7b4b8e0338a29475c8934"
os = "macos"

    [[electronjs_app.download]]
    sha256 = "7f7f07065b5bc62523cc317c9ef3560b81c7f0a5cdcebbc4a8426033620a401e"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v8.3.0%2B0/ElectronJS-8.3.0+0-x86_64-apple-darwin14.tar.gz"
[[electronjs_app]]
arch = "i686"
git-tree-sha1 = "9008aff40ba9017e5ff1b605b9fa2a09847d5cf1"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "2884ced1fa3422479f878eaf76687971ee7f2b1cd8e9eba29ea130eb85ff71e0"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v8.3.0%2B0/ElectronJS-8.3.0+0-i686-w64-mingw32.tar.gz"
[[electronjs_app]]
arch = "x86_64"
git-tree-sha1 = "ed9c2e8058ff0c3aff41ffb4fdd3e352f4890c0f"
os = "windows"

    [[electronjs_app.download]]
    sha256 = "7cfd29cfdb52a40bea7612c2d391a89b3ac6af430ff743c4d0153d25b2fbbfeb"
    url = "https://github.com/davidanthoff/ElectronBuilder/releases/download/v8.3.0%2B0/ElectronJS-8.3.0+0-x86_64-w64-mingw32.tar.gz"
